Adding hostipc policy for new scc
openshift-4-compliance/openshift-4-compliance-automation pull request #36
Opened 2021-04-13 08:44 UTC by igorkchyts

Adding hostipc policy that ensures that created scc are not allowing access to the host PID and IPC namespaces

2021-04-13 14:55 UTC, michaelkotelnikov requested changes

2021-04-13 14:55 UTC, michaelkotelnikov commented on kyverno/authorization/disallow-host-ipc.yaml
> +          =(allowHostIPC): "false"
Exclude the SCCs that allow HostIPC by default.

2021-04-13 14:55 UTC, michaelkotelnikov commented on kyverno/authorization/disallow-host-ipc.yaml
> +        message: "Use of host PID ands IPC namespaces is not allowed"
Provide a unique message for violations caused by editing `pod` resources

2021-04-13 14:55 UTC, michaelkotelnikov commented on kyverno/authorization/disallow-host-ipc.yaml
> +        message: "Use of host PID ands IPC namespaces is not allowed"
provide a unique message for violations caused by editing `ssc` resources.

2021-04-13 14:55 UTC, michaelkotelnikov commented on kyverno/README.md
> +[disallow-host-ipc-scc](./authorization/disallow-host-ipc-scc.yaml) | Ensures that access to the host PID and IPC namespaces is restricted |
Provide more information tothe description.

2021-04-25 08:01 UTC, michaelkotelnikov requested changes

2021-04-25 08:01 UTC, michaelkotelnikov commented on kyverno/authorization/host-namespaces/README.md
> +Access to several host namespaces (Process ID namespaces, Inter-Process Communication namespaces, and network namespaces) allow access to shared information and can be used to elevate privileges.
Change `allow` to `allows`. @igorkchyts

2021-04-25 14:18 UTC, michaelkotelnikov requested changes

2021-04-26 09:37 UTC, igorkchyts commented on kyverno/authorization/host-namespaces/disallow-host-ipc.yaml
> +          name: hostaccess
@michaelkotelnikov Resolved by adding 'exclude.resource.name' for each SCC
Please validate

2021-04-26 12:30 UTC, igorkchyts commented on kyverno/authorization/host-namespaces/disallow-host-ipc.yaml
> +          name: hostaccess
@michaelkotelnikov 
The rule works as expected for 'Pod' resource types. 
After playing around for a while I keep getting ignored when excluding "SecurityContextConstaints". 
Open new issue in kyverno :
https://github.com/kyverno/kyverno/issues/1836

2021-04-29 10:14 UTC, michaelkotelnikov approved these changes
@igorkchyts Looks good to me now.

2021-04-29 10:14 UTC, merged